[package]
name = "rustmate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18.2", features = ["full"] }
byteorder = "1.4.3"
libmath = "0.2.1"
hex = "0.4.3"
